export const COLORS = {
  WHITE: '#fff',
  BLACK: '#121318',
  GRAY: '#DCDCDD',
  DARKGRAY: '#a3a3a3',
  GREEN: '#315917',
  RED: '#C70039',
  DARKBLUE: '#070f24',
};

export const darkTheme = {
  PRIMARY_COLOR: COLORS.BLACK,
  SECONDARY_COLOR: COLORS.WHITE,
  TITLE_COLOR: COLORS.WHITE,
  BACKGROUND_COLOR: COLORS.BLACK,
  BUTTON_COLOR: COLORS.WHITE,
  BUTTON_TITLE_COLOR: COLORS.BLACK,
};
export const lightTheme = {
  PRIMARY_COLOR: COLORS.WHITE,
  SECONDARY_COLOR: COLORS.BLACK,
  TITLE_COLOR: COLORS.BLACK,
  BACKGROUND_COLOR: COLORS.WHITE,
  BUTTON_COLOR: COLORS.BLACK,
  BUTTON_TITLE_COLOR: COLORS.WHITE,
};
